import type { CSSProperties } from 'react';
import { colors, radius, size } from '@tslprb/design-tokens';

// Website-only presentation inspired by brollyexamprep.com.
// Shared mobile tokens and exam success/error semantics stay intact.
export const themeVariables = {
  '--background': '#ffffff',
  '--foreground': '#111214',
  '--card': '#ffffff',
  '--card-foreground': '#111214',
  '--popover': '#ffffff',
  '--popover-foreground': '#111214',
  '--primary': '#111214',
  '--primary-foreground': '#ffffff',
  '--secondary': '#f6f7f8',
  '--secondary-foreground': '#111214',
  '--muted': '#f6f7f8',
  '--muted-foreground': '#606670',
  '--accent': '#fffed0',
  '--accent-foreground': '#111214',
  '--destructive': colors.dangerInk,
  '--destructive-foreground': colors.white,
  '--border': '#e2e5e9',
  '--input': '#9399a2',
  '--ring': '#777500',
  '--chart-1': colors.ink,
  '--chart-2': colors.accentInk,
  '--chart-3': colors.navy,
  '--chart-4': colors.okInk,
  '--chart-5': colors.dangerInk,
  '--radius': `${radius.lg}px`,
  '--brand-radius-sm': `${radius.sm}px`,
  '--brand-radius-md': '10px',
  '--brand-radius-lg': '18px',
  '--brand-radius-xl': `${radius.xl}px`,
  '--brand-font-sans': '"Plus Jakarta Sans", Inter, NotoSansTelugu, system-ui, sans-serif',
  '--touch-size': `${size.touch}px`,
  '--touch-size-lg': `${size.touchLg}px`,
  '--brand-scrim': colors.scrimHeavy,
  '--brand-gold': '#fff84b',
  '--brand-danger-tint': colors.dangerTint,
  '--brand-success': colors.okInk,
  '--brand-success-tint': colors.okTint,
} as CSSProperties;
